# Site
name: 'The Finance Notes'
description: 'learning new things everyday'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'gopesh-sharma'
email: 'thefinancenotes@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:categories/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
  self:
    name: Gopesh Sharma
    picture: assets/images/gopesh-bio-150.jpg
    email: gopesh9@gmail.com
    twitter: https://twitter.com/gopu18
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Gopesh
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

feed:
  path: atom.xml

footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/gopesh-sharma-28185483/
    icon: fab fa-linkedin-in
  - title: Twitter
    url: https://twitter.com/thefinancenote
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/thefinance.notes
    icon: fab fa-instagram
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]